# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8941d0a9348c1fdb8780d97b722839b5af0f2855b61d8099575c26ccb8784fe2a86976b68979b16aebaec88c67c652d01f3a2ea6d15bcbcddfa082b2eac3c5

test:
  secret_key_base: c1095bf8a3fbceb8b0d3a587ce9a03708c64f5f73d47b42de510273e854f619cc4e85431e54871df0aa88096850ba421c4c624cced8d44729ea697177bf1edde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
